# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171206_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogTitle',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
